= README

== Purpose

Unixorn aspires to be a Unix-like environment that:

* can be embedded into a website

* can be interacted with via the built-in shell

* comes with a set of built-in commands

* can be extended with additional commands

== Usage

=== In React

....
import React, { Component } from 'react'

import Unixorn from 'unixorn'

const configuration = {}

class Example extends Component {
  render() {
    return <Unixorn {...configuration} />
  }
}
....

=== Without React

....
import { initUnixorn } from 'unixorn'

const configuration = {}

const nonReactDomNode = document.getElementById('example')

initUnixorn(nonReactDomNode, configuration)
....

== Development

=== To install dependencies

Execute `yarn install`.

=== To build

Execute `yarn run build`.

=== To run

Execute `yarn start`.

=== To run example app

Execute `yarn install` and `yarn start` in the example folder.

== Configuration

[%header,cols="1,1,1a"]
.Configuration
|===
|Name
|Type
|Description

|startupMessage
|string
|The message to display when the terminal starts.

|===
